openapi: 3.0.0
info:
  title: RAG Chatbot for Published Books API
  description: API for a Retrieval-Augmented Generation (RAG) chatbot that enables users to ask questions about published book content
  version: 1.0.0
servers:
  - url: https://api.ragchatbot.com/v1
    description: Production server
  - url: https://staging-api.ragchatbot.com/v1
    description: Staging server
  - url: http://localhost:8000
    description: Development server

paths:
  /ingest:
    post:
      summary: Upload and process a book
      description: Allows users to upload a book (PDF/EPUB) for processing and indexing
      operationId: ingestBook
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - book_id
                - title
              properties:
                file:
                  type: string
                  format: binary
                  description: The book file (PDF/EPUB) to upload
                book_id:
                  type: string
                  description: A unique identifier for the book
                  example: "book_uuid_123"
                title:
                  type: string
                  description: Title of the book
                  example: "The Great Gatsby"
                author:
                  type: string
                  description: Author of the book
                  example: "F. Scott Fitzgerald"
                publisher:
                  type: string
                  description: Publisher of the book
                  example: "Scribner"
                metadata:
                  type: object
                  description: Additional metadata about the book
                  properties:
                    language:
                      type: string
                      example: "en"
                    isbn:
                      type: string
                      example: "978-0743273565"
      responses:
        '202':
          description: Book ingestion accepted and processing started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '400':
          description: Invalid file format or missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '413':
          description: File too large (> 500MB)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error during ingestion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Ingestion

  /ingest/status/{job_id}:
    get:
      summary: Poll ingestion job status
      description: Check the status of a book ingestion job
      operationId: getIngestionStatus
      parameters:
        - name: job_id
          in: path
          required: true
          description: The ID of the ingestion job
          schema:
            type: string
            example: "ingest_job_uuid_456"
      responses:
        '200':
          description: Ingestion job status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionStatusResponse'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Ingestion

  /query:
    post:
      summary: Answer questions about full book
      description: Ask questions about the content of a specific book
      operationId: queryFullBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Answer to the query with sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid query format or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Book not found in system
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Query

  /query-selection:
    post:
      summary: Answer questions based on user-selected text
      description: Answer questions based only on a specific text selection made by the user
      operationId: querySelection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectionQueryRequest'
      responses:
        '200':
          description: Answer to the query based on selection with sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelectionQueryResponse'
        '400':
          description: Invalid query format or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Selection not found in system
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Query

  /conversations:
    post:
      summary: Create a new conversation session
      description: Initialize a new conversation session with a book
      operationId: createConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConversationRequest'
      responses:
        '201':
          description: New conversation session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateConversationResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Conversation

  /conversations/{session_id}:
    get:
      summary: Retrieve conversation history
      description: Get the history of messages in a conversation session
      operationId: getConversation
      parameters:
        - name: session_id
          in: path
          required: true
          description: The ID of the conversation session
          schema:
            type: string
            example: "session_uuid_999"
      responses:
        '200':
          description: Conversation history retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '404':
          description: Conversation session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Conversation

components:
  schemas:
    IngestionResponse:
      type: object
      properties:
        job_id:
          type: string
          description: ID of the ingestion job
          example: "ingest_job_uuid_456"
        status:
          type: string
          description: Status of the job
          example: "processing"
        book_id:
          type: string
          description: ID of the book being processed
          example: "book_uuid_123"
        estimated_completion:
          type: string
          format: date-time
          description: Estimated completion time
          example: "2024-12-17T15:45:00Z"
        webhook_url:
          type: string
          description: URL for webhook notifications (optional)
          example: "https://yoursite.com/webhooks/ingest"
      required:
        - job_id
        - status
        - book_id

    IngestionStatusResponse:
      type: object
      properties:
        job_id:
          type: string
          description: ID of the ingestion job
          example: "ingest_job_uuid_456"
        status:
          type: string
          description: Current status of the job
          example: "completed"
        document_id:
          type: string
          description: ID of the processed document
          example: "doc_uuid_789"
        chunks_created:
          type: integer
          description: Number of text chunks created
          example: 2847
        vectors_indexed:
          type: integer
          description: Number of vectors indexed in the vector store
          example: 2847
        total_tokens:
          type: integer
          description: Total number of tokens processed
          example: 1456200
        storage_used_mb:
          type: number
          description: Storage used in MB
          example: 45.2
        duration_seconds:
          type: integer
          description: Processing duration in seconds
          example: 420

    QueryRequest:
      type: object
      properties:
        query:
          type: string
          description: The user's question
          example: "What is the significance of the green light?"
        document_id:
          type: string
          description: ID of the document to query
          example: "doc_uuid_789"
        session_id:
          type: string
          description: Session identifier (optional)
          example: "session_uuid_999"
        user_id:
          type: string
          description: User identifier (optional)
          example: "user_123"
        top_k:
          type: integer
          description: Number of relevant chunks to retrieve (default: 5)
          default: 5
          example: 5
        confidence_threshold:
          type: number
          description: Minimum confidence threshold for relevant chunks (default: 0.7)
          default: 0.7
          example: 0.7
      required:
        - query
        - document_id

    QueryResponse:
      type: object
      properties:
        query:
          type: string
          description: The original user query
          example: "What is the significance of the green light?"
        answer:
          type: string
          description: The generated answer
          example: "The green light at the end of Daisy's dock is a symbol of Gatsby's dreams and the American Dream itself..."
        sources:
          type: array
          description: List of source chunks used to generate the answer
          items:
            $ref: '#/components/schemas/SourceChunk'
        confidence:
          type: number
          description: Overall confidence score of the answer
          example: 0.89
        latency_ms:
          type: integer
          description: Time taken to generate the answer in milliseconds
          example: 1845
        citations:
          type: string
          description: Formatted citations
          example: "[Chapter 1, Page 23] and [Chapter 5, Page 98]"
        conversation_id:
          type: string
          description: ID of the conversation entry created
          example: "conv_uuid_111"

    SelectionQueryRequest:
      type: object
      properties:
        query:
          type: string
          description: The user's question about the selection
          example: "What does this passage mean?"
        selection_id:
          type: string
          description: ID of the user's text selection
          example: "selection_uuid_222"
        document_id:
          type: string
          description: ID of the document containing the selection
          example: "doc_uuid_789"
        selected_text:
          type: string
          description: The actual text that was selected by the user
          example: "It was a beautiful morning and the sun was rising..."
        session_id:
          type: string
          description: Session identifier (optional)
          example: "session_uuid_999"
      required:
        - query
        - selection_id
        - selected_text
        - document_id

    SelectionQueryResponse:
      type: object
      properties:
        query:
          type: string
          description: The original user query
          example: "What does this passage mean?"
        answer:
          type: string
          description: The generated answer based on selected text
          example: "This passage establishes the setting with vivid imagery..."
        sources:
          type: array
          description: List of source chunks from the selection used to generate the answer
          items:
            $ref: '#/components/schemas/SelectionSourceChunk'
        scope:
          type: string
          description: Indicates that answer is restricted to selection
          example: "restricted_to_selection"
        citation:
          type: string
          description: Citation indicating the source
          example: "[From your selected text]"
        conversation_id:
          type: string
          description: ID of the conversation entry created
          example: "conv_uuid_333"

    SourceChunk:
      type: object
      properties:
        chunk_id:
          type: string
          description: ID of the source chunk
          example: "chunk_234"
        chapter:
          type: integer
          description: Chapter number where the chunk appears
          example: 1
        page:
          type: integer
          description: Page number where the chunk appears
          example: 23
        text:
          type: string
          description: Preview of the source text
          example: "In my younger and more vulnerable years..."
        similarity_score:
          type: number
          description: Similarity score to the query
          example: 0.92

    SelectionSourceChunk:
      type: object
      properties:
        selection_id:
          type: string
          description: ID of the user selection
          example: "selection_uuid_222"
        position:
          type: string
          description: Position indicator for selected text
          example: "user-selected"
        text:
          type: string
          description: The selected text content
          example: "It was a beautiful morning..."
        similarity_score:
          type: number
          description: Similarity score to the query
          example: 1.0

    CreateConversationRequest:
      type: object
      properties:
        document_id:
          type: string
          description: ID of the document for the conversation
          example: "doc_uuid_789"
        user_id:
          type: string
          description: User identifier (optional)
          example: "user_123"
        metadata:
          type: object
          description: Additional metadata for the conversation
          properties:
            device:
              type: string
              example: "web"
            browser:
              type: string
              example: "Chrome"
      required:
        - document_id

    CreateConversationResponse:
      type: object
      properties:
        session_id:
          type: string
          description: ID of the created conversation session
          example: "session_uuid_999"
        document_id:
          type: string
          description: ID of the associated document
          example: "doc_uuid_789"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the session was created
          example: "2024-12-17T12:00:00Z"
        ttl_hours:
          type: integer
          description: Time-to-live for the session in hours
          example: 24

    ConversationResponse:
      type: object
      properties:
        session_id:
          type: string
          description: ID of the conversation session
          example: "session_uuid_999"
        document_id:
          type: string
          description: ID of the associated document
          example: "doc_uuid_789"
        message_count:
          type: integer
          description: Number of messages in the conversation
          example: 12
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    Message:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the message
          example: "msg_1"
        type:
          type: string
          description: Type of the message (user or assistant)
          enum: [user, assistant]
          example: "user"
        content:
          type: string
          description: Content of the message
          example: "What is the main theme?"
        sources:
          type: array
          description: Sources referenced in the message (for assistant messages)
          items:
            $ref: '#/components/schemas/SourceChunk'
        timestamp:
          type: string
          format: date-time
          description: When the message was created
          example: "2024-12-17T12:01:00Z"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: A human-readable error message
          example: "Invalid file format"
        message:
          type: string
          description: Additional details about the error
          example: "Only PDF and EPUB files are supported"
        code:
          type: string
          description: Error code for programmatic handling
          example: "INVALID_FILE_FORMAT"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

tags:
  - name: Ingestion
    description: Endpoints related to book ingestion and processing
  - name: Query
    description: Endpoints for querying book content
  - name: Conversation
    description: Endpoints for conversation management