openapi: 3.0.0
info:
  title: Frontend Authentication API
  version: 1.0.0
  description: API endpoints for user authentication (login, registration)
servers:
  - url: /api/auth # Assuming the backend auth API is prefixed with /api/auth
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid registration data
        '409':
          description: User with provided email already exists
  /login:
    post:
      summary: Authenticate user and get access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
  /logout:
    post:
      summary: Invalidate user session/token
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Successfully logged out
        '401':
          description: Unauthorized
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: User's password
        username:
          type: string
          description: Optional username
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: User's password
    AuthResponse:
      type: object
      required:
        - accessToken
        - user
      properties:
        accessToken:
          type: string
          description: JWT access token
        refreshToken:
          type: string
          description: Refresh token (optional, could be HttpOnly cookie)
        user:
          $ref: '#/components/schemas/UserProfile'
    UserProfile:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: string
          description: User ID
        email:
          type: string
          format: email
          description: User's email address
        username:
          type: string
          description: Optional username
        roles:
          type: array
          items:
            type: string
          description: List of user roles
