import rclpy
from rclpy.node import Node
from std_msgs.msg import String
from geometry_msgs.msg import PoseStamped # Example for a 'move_to' action
import json

class LLMTaskPlannerNode(Node):
    def __init__(self):
        super().__init__('llm_task_planner_node')
        self.command_subscription = self.create_subscription(
            String,
            '/transcribed_text', # Topic from Whisper ROS Node
            self.command_callback,
            10
        )
        # Assuming a generic action topic for simplicity; in reality, this might be more specific
        self.action_publisher = self.create_publisher(
            String, # Or a custom message type for structured actions
            '/robot_actions',
            10
        )
        self.get_logger().info('LLM Task Planner Node started. Waiting for transcribed commands...')

        # Define available robot actions (simplified for this example)
        self.available_actions = [
            "move_to(location)",
            "pick_up(object_name)",
            "place_down(object_name, location)",
            "open(object)",
            "close(object)",
            "detect_object(object_name)"
        ]

    def _mock_llm_call(self, natural_language_command: str) -> str:
        """
        Mocks an LLM API call to generate a sequence of robot actions.
        In a real scenario, this would involve an actual API request to an LLM.
        """
        self.get_logger().info(f'Mock LLM processing command: "{natural_language_command}"')
        
        # Simple rule-based mocking for demonstration
        if "go to the kitchen" in natural_language_command.lower():
            action_plan = [
                {"action": "move_to", "parameters": {"location": "kitchen"}}
            ]
        elif "pick up the red block" in natural_language_command.lower():
            action_plan = [
                {"action": "detect_object", "parameters": {"object_name": "red block"}},
                {"action": "pick_up", "parameters": {"object_name": "red block"}}
            ]
        elif "bring me a drink" in natural_language_command.lower():
            action_plan = [
                {"action": "move_to", "parameters": {"location": "kitchen"}},
                {"action": "open", "parameters": {"object": "fridge"}},
                {"action": "detect_object", "parameters": {"object_name": "drink"}},
                {"action": "pick_up", "parameters": {"object_name": "drink"}},
                {"action": "close", "parameters": {"object": "fridge"}},
                {"action": "move_to", "parameters": {"location": "user"}}
            ]
        else:
            self.get_logger().warn(f'Mock LLM could not plan for: "{natural_language_command}"')
            return "[]" # Return empty plan

        return json.dumps(action_plan)

    def command_callback(self, msg: String):
        self.get_logger().info(f'Received natural language command: "{msg.data}"')
        
        # Call the (mock) LLM to get an action plan
        action_plan_json = self._mock_llm_call(msg.data)
        
        if action_plan_json:
            action_msg = String()
            action_msg.data = action_plan_json
            self.action_publisher.publish(action_msg)
            self.get_logger().info(f'Published action plan: {action_plan_json}')
        else:
            self.get_logger().warn('No action plan generated by LLM.')

def main(args=None):
    rclpy.init(args=args)
    llm_planner_node = LLMTaskPlannerNode()
    rclpy.spin(llm_planner_node)
    llm_planner_node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
